name: Basic CI Workflow


  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Display a message
        run: echo "Hello, GitHub Actions!"
